/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      
      colors: {
        background: "#121212",
        text: "#e0e0e0",
        accent: "#F4D9D0",
        customGreen: '#cef2db',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'], 
        pix: ['pix', 'sans-serif'],
        pixel: ['pixel', 'sans-serif'],
        kiwi: ['kiwi', 'sans-serif'],
        pixround: ['pixround', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        chakra: ['Chakra Petch', 'sans-serif'],
        gotic: ['DotGothic16', 'sans-serif'],
        major: ['Major Mono Display', 'sans-serif'],
        orbi: ['Orbitron', 'sans-serif'],
        mono: ['Roboto Mono', 'monospace'],
        sourceCode: ['Source Code Pro', 'monospace'], 
      },
      animation: {
        'bounce-slow': 'bounce 3s ease-in-out infinite',
        'pulse-slow': 'pulse 2s ease-in-out infinite',
        'shake': 'shake 1s ease-in-out infinite',
        'fade-in': 'fadeIn 1.5s ease-out infinite forwards',
        'move-up': 'moveUp 2s ease-in-out infinite',
        fadeOut: 'fadeOut 1.5s ease-out infinite',
        zoomin: 'zoom-in 1s ease-in-out 0.25s 1',
        zoomout: 'zoom-out 1s ease-in-out 0.25s 1',
        tada: 'tada 1s ease-in-out infinite',
        tadaOne: 'tada 1s ease-in-out 0.25 1',
        spinnergrow: 'spinner-grow 1s ease-in-out 0.25s 1',
        placeholderwave: 'placeholder-wave 1s ease-in-out 0.25s 1',
        showUpClock: 'showUpClock 1s ease-in-out 0.25s 1',
        dropin: 'dropIn  0.5s ease-in-out 0.25s 1',
        dropout: 'drop-out 0.5s ease-in-out 0.25s 1',
        flyin: 'flyin 0.6s ease-in-out 0.25s 1',
        flyout: 'flyout 0.6s ease-in-out 0.25s 1',
        flyoutup: 'fly-out-up 0.6s ease-in-out 0.25s 1',
        flyoutdown: 'fly-out-down 0.6s ease-in-out 0.25s 1',
        jiggle: 'jiggle 0.6s ease-in-out 0.25s 1',
        flash: 'flash 0.6s ease-in-out infinite',
        flashSlow: 'flash 1.2s ease-in-out infinite',
        glowTeal: 'glowTeal 1.6s ease-in-out infinite',
        glowPink: 'glowPink 5s ease-in-out infinite',
        glowPurple: 'glowPurple 1.6s ease-in-out infinite',
        glowAmber: 'glowAmber 1.6s ease-in-out infinite',
        glowOrange: 'glowOrange 1.6s ease-in-out infinite',
        glowRose: 'glowRose 1.6s ease-in-out infinite',
        glowEme: 'glowEme 1.6s ease-in-out infinite',
        zoomIn: 'zoomin 1s ease-out 0.25s 1',
        zoomOut: 'zoomout 1s ease-out 0.25s 1',
        flipx: 'flipx 1.5s ease-out infinite',
        flippy: 'flippy 1.5s ease-out infinite',
        flipyup: 'flipyup 1s ease 0.25s 1',
        flippydown: 'flippy-down 1s ease 0.25s 1',
        pulseright: 'pulse-right 1s ease-in-out infinite',
        showUpTada: 'showUpTada 1.5s ease-in-out 1', 
        rotateDisk: 'rotateDisk 3s linear infinite',
        glowText: 'glowText 1.5s ease-in-out infinite alternate',
        fadeOutScale: 'fadeOutScale 0.5s ease-out forwards',
        disappear: 'disappear 1.5s ease-out forwards',
        reduceAndFade: 'reduceAndFade 0.1s ease-out forwards',
        colorCycle: 'colorCycle 2.5s infinite',
        colorFast: 'colorCycle 0.8s infinite',
        colorSlow: 'colorCycle 6s infinite',
        blinkAndBounce: 'blinkAndBounce 4s ease-in-out infinite',
      },
      keyframes: {
        shake: {
          '0%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-5px)' },
          '50%': { transform: 'translateX(5px)' },
          '75%': { transform: 'translateX(-5px)' },
          '100%': { transform: 'translateX(0)' },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        fadeOut: {
          '0%': { opacity: 1 },
          '100%': { opacity: 0 },
        },
        tada: {
          "0%": { transform: "scale(1)" },
          "10%": { transform: "scale(1.1)" },
          "20%": { transform: "scale(1)" },
          "30%": { transform: "scale(1.1)" },
          "40%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.1)" },
          "60%": { transform: "scale(1)" },
          "70%": { transform: "scale(1.1)" },
          "80%": { transform: "scale(1)" },
          "90%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)" },
        },
        flipx: {
          '0%': { transform: 'rotateX(0deg)' },
          '100%': { transform: 'rotateX(180deg)' },
        },
        flipy: {
          '0%': { transform: 'rotateY(0deg)' },
          '100%': { transform: 'rotateY(180deg)' },
        },
        glowTeal: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(45 212 191)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowPink: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(249 168 212)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowPurple: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(147 51 234)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowAmber: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(245 158 11)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowOrange: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(194 65 12)'},
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowEme: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(52 211 153)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        glowRose: {
          '0%': { boxShadow: '0 0 5px #fff' },
          '50%': { boxShadow: '0 0 20px #fff, 0 0 21px rgb(225 29 72)' },
          '100%': { boxShadow: '0 0 5px #fff' },
        },
        zoomin: {
          '0%': { transform: 'scale(0)' },
          '100%': { transform: 'scale(1)' },
        },
        jiggle: {
          '0%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-10px)' },
          '50%': { transform: 'translateX(10px)' },
          '75%': { transform: 'translateX(-5px)' },
          '100%': { transform: 'translateX(0)' },
        },
        flash: {
          '0%': { opacity: '1' },
          '50%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        flyin: {
          '0%': { transform: 'translateX(-100%)', opacity: 0 },
          '100%': { transform: 'translateX(0)', opacity: 1 },
        },
        flyout: {
          '0%': { transform: 'translateX(0)', opacity: 1 },
          '100%': { transform: 'translateX(-100%)', opacity: 0 },
        },
        spinnergrow: {
          '0%': { transform: 'scale(0)', opacity: 1 },
          '50%': { transform: 'scale(1)', opacity: 1 },
          '100%': { transform: 'scale(0)', opacity: 1 },
        },
        placeholderwave: {
        '0%': { backgroundPosition: '-200px 0' },
        '100%': { backgroundPosition: '200px 0' },
      },
      dropIn: {
        '0%': { transform: 'translateY(-100%)', opacity: 0 },
        '100%': { transform: 'translateY(0)', opacity: 1 },
      },
      showUpClock: {
        '0%': { transform: 'scale(0)', opacity: 0 },
        '100%': { transform: 'scale(1)', opacity: 1 },
      },
      spinnerGrow: {
        '0%': { transform: 'scale(0)', opacity: 1 },
        '50%': { transform: 'scale(1)', opacity: 1 },
        '100%': { transform: 'scale(0)', opacity: 1 },
      },
      flyIn: {
        '0%': { transform: 'translateX(-100%)', opacity: 0 },
        '100%': { transform: 'translateX(0)', opacity: 1 },
      },
      showUpTada: {
        
        '60%': { transform: 'scale(0.9)' }, 
        '70%': { transform: 'scale(1.1)' },
        '80%': { transform: 'scale(1)' },
        '90%': { transform: 'scale(1.1)' },
        '100%': { transform: 'scale(1)' },
        
      },
      rotateDisk: {
        '0%': { transform: 'rotate(0deg)' },
        '100%': { transform: 'rotate(360deg)' },
      },
      glowText: {
        '0%': { textShadow: '0 0 5px #000, 0 0 10px #FF69B4, 0 0 15px #000' },
        '100%': { textShadow: '0 0 10px #000, 0 0 15px #4B0082, 0 0 30px #00CED1' },
      },
      fadeOutScale: {
        '0%': { opacity: 1, transform: 'scale(1)' },
        '100%': { opacity: 0, transform: 'scale(0.9)' },
    },  
      reduceAndFade: {
        '0%': { transform: 'scale(1)', opacity: 1 },
        '60%': { transform: 'scale(0.9)', opacity: 0.8 },
        '80%': { transform: 'scale(0.6)', opacity: 0.4 },
        '100%': { transform: 'scale(0.3)', opacity: 0 },
      },
      colorCycle: {
        '0%': { color: '#f472b6' }, 
        '5%': { color: '#db85c7' }, 
        '16%': { color: '#c084fc' },
        '33%': { color: '#22d3ee' },
        '50%': { color: '#14b8a6' },
        '66%': { color: '#19ff4b' }, 
        '83%': { color: '#facc15' }, 
        '93%': { color: '#a855f7' }, 
        '100%': { color: '#f472b6' }, 
      },
      blinkAndBounce: {
        '0%, 20%, 40%': { opacity: '1', transform: 'scale(1)' },
        '10%, 30%': { opacity: '0' },
        '50%': { transform: 'scale(1.2)' },
        '70%': { transform: 'scale(0.95)' },
        '80%': { transform: 'scale(1.05)' },
        '90%, 100%': { opacity: '1', transform: 'scale(1)' }, // Pausa hasta el final del ciclo
      },
      },
    },
  },
  plugins: [],
}